version: '2'
services:
  what_does_the_fox_say:
    build:
      dockerfile: ./Dockerfile
      context: ./what_does_the_fox_say
      args:
        - FLAG=0000000000
        - FLAG_FILE=flag.txt
  sql_injection:
    build:
      dockerfile: ./Dockerfile
      context: ./sql_injection
    environment:
      - FLAG=0000000000
  ph-shop:
    build:
      dockerfile: ./Dockerfile
      context: ./ph-shop
    environment:
      - FLAG=000000000
  ssti:
    build:
      dockerfile: ./Dockerfile
      context: ./ssti
      args:
        - FLAG=000000
        - FLAG_FILE=flag.txt
    user: 1023:1023
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./_data:/var/lib/mysql
  proxy:
    build:
      dockerfile: ./proxy.dockerfile
      context: ./
    ports:
      - 10001:10001
      - 10002:10002
      - 10003:10003
      - 10004:10004
      - 10005:10005
